# Generated by Django 2.2.12 on 2020-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_offered',
            field=models.BooleanField(default=False),
        ),
    ]
